# Generated by Django 5.2 on 2025-05-04 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('documentTypeId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Tipo de Documento')),
                ('typeName', models.CharField(max_length=50, verbose_name='Nombre del Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('personTypeId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Tipo de Persona')),
                ('typeName', models.CharField(max_length=20, verbose_name='Nombre del Tipo de Persona')),
            ],
            options={
                'verbose_name': 'Tipos de persona',
                'verbose_name_plural': 'Tipos de persona',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('document', models.CharField(db_index=True, max_length=12, verbose_name='Documento')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(db_index=True, max_length=10, verbose_name='Teléfono')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Dirección')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_with_document_type', to='users.documenttype', verbose_name='Tipo de Documento')),
                ('person_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_with_person_type', to='users.persontype', verbose_name='Tipo de Persona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
