# Generated by Django 5.2 on 2025-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Documento'),
        ),
    ]
