# Generated by Django 5.2 on 2025-05-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('users', '0002_alter_customuser_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
