# Generated by Django 5.2 on 2025-05-27 05:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0004_empresa_tamaño_empresa_url'),
        ('normas', '0010_alter_caracteristica_options_and_more'),
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_evaluacion', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Código único de evaluación')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('puntuacion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuación total (%)')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones generales de la evaluación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='empresa.empresa', verbose_name='Empresa')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario evaluador')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='normas.norma', verbose_name='Norma aplicada')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='software.software', verbose_name='Software evaluado')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'unique_together': {('software', 'norma', 'evaluador')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_obtenida', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntuación obtenida (%)')),
                ('puntuacion_maxima', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Puntuación máxima (%)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones de la característica')),
                ('fecha_calificacion', models.DateTimeField(auto_now=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='normas.caracteristica')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_caracteristica', to='evaluaciones.evaluacion')),
            ],
            options={
                'verbose_name': 'Calificación de Característica',
                'verbose_name_plural': 'Calificaciones de Características',
                'unique_together': {('evaluacion', 'caracteristica')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionSubCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Puntos obtenidos (0-3)')),
                ('puntos_maximo', models.IntegerField(default=3, verbose_name='Puntos máximos')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación/Justificación')),
                ('evidencia_url', models.URLField(blank=True, null=True, verbose_name='URL de evidencia (opcional)')),
                ('fecha_calificacion', models.DateTimeField(auto_now=True)),
                ('calificacion_caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_subcaracteristica', to='evaluaciones.calificacioncaracteristica')),
                ('subcaracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='normas.subcaracteristica')),
            ],
            options={
                'verbose_name': 'Calificación de Subcaracterística',
                'verbose_name_plural': 'Calificaciones de Subcaracterísticas',
                'unique_together': {('calificacion_caracteristica', 'subcaracteristica')},
            },
        ),
    ]
