# Generated by Django 5.2 on 2025-05-27 09:57

import django.core.validators
from django.db import migrations, models
from decimal import Decimal

class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncaracteristica',
            name='porcentaje_asignado',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Porcentaje del peso de esta característica en esta evaluación específica',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
                verbose_name='Porcentaje asignado a esta característica (%)'
            ),
        ),
    ]
