# Generated by Django 5.2 on 2025-05-14 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('normas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='enunciado',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_empresa', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntos',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
