# Generated by Django 5.2 on 2025-05-14 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('normas', '0002_remove_pregunta_enunciado_pregunta_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionSubCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('puntos', models.IntegerField()),
                ('valor_maximo', models.IntegerField(default=3)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_empresa', to='empresa.empresa')),
                ('subcaracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='normas.subcaracteristica')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
