# Generated by Django 5.2 on 2025-05-18 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_calificacionsubcaracteristica_delete_pregunta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionsubcaracteristica',
            name='valor_maximo',
        ),
        migrations.AlterField(
            model_name='calificacionsubcaracteristica',
            name='puntos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='calificacionsubcaracteristica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
