# Generated by Django 5.2 on 2025-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0004_remove_calificacionsubcaracteristica_valor_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionsubcaracteristica',
            name='codigo_evaluacion',
            field=models.CharField(db_default='', help_text='condigo unico para evaluacion', max_length=10, verbose_name='Codigo unico para evaluacion'),
        ),
    ]
