# Generated by Django 5.2 on 2025-05-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0006_rename_codigo_evaluacion_calificacionsubcaracteristica_codigo_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionsubcaracteristica',
            name='fecha_cracion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creacion', verbose_name='Fecha de creaion'),
            preserve_default=False,
        ),
    ]
