# Generated by Django 5.2 on 2025-05-18 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_codigo_empresa_alter_empresa_fecha_creacion'),
        ('normas', '0007_calificacionsubcaracteristica_fecha_cracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionsubcaracteristica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_empresa', to='empresa.empresa'),
        ),
    ]
