# Generated by Django 5.2 on 2025-05-26 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0008_alter_calificacionsubcaracteristica_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma',
            options={'permissions': [('can_approve_norma', 'Puede aprobar normas'), ('can_review_norma', 'Puede revisar normas'), ('can_create_norma', 'Puede crear normas')], 'verbose_name': 'Norma', 'verbose_name_plural': 'Normas'},
        ),
        migrations.AddField(
            model_name='norma',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='norma',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('obsoleta', 'Obsoleta')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='norma',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='norma',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='norma',
            name='version',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
