# Generated by Django 5.2 on 2025-05-27 04:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0009_alter_norma_options_norma_creado_por_norma_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Característica', 'verbose_name_plural': 'Características'},
        ),
        migrations.AlterModelOptions(
            name='subcaracteristica',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Subcaracterística', 'verbose_name_plural': 'Subcaracterísticas'},
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='es_obligatoria',
            field=models.BooleanField(default=True, verbose_name='¿Es obligatoria en evaluaciones?'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de presentación'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='porcentaje_peso',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso de esta característica en la evaluación total. Todas deben sumar 100%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de peso (%)'),
        ),
        migrations.AddField(
            model_name='subcaracteristica',
            name='criterios_evaluacion',
            field=models.TextField(blank=True, help_text='Guía específica para evaluar esta subcaracterística', null=True, verbose_name='Criterios de evaluación'),
        ),
        migrations.AddField(
            model_name='subcaracteristica',
            name='es_obligatoria',
            field=models.BooleanField(default=True, verbose_name='¿Es obligatoria en evaluaciones?'),
        ),
        migrations.AddField(
            model_name='subcaracteristica',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de presentación'),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristica',
            unique_together={('norma', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='subcaracteristica',
            unique_together={('caracteristica', 'nombre')},
        ),
        migrations.DeleteModel(
            name='CalificacionSubCaracteristica',
        ),
    ]
