# Generated by Django 5.2 on 2025-05-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_codigo_empresa_alter_empresa_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_empresa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
