# Generated by Django 5.2 on 2025-05-18 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de impactos')),
                ('valor', models.IntegerField(help_text='Valor de impacto Debe de ser entre 0 y 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='OpcionTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de opcion de tratamiento de riego')),
            ],
        ),
        migrations.CreateModel(
            name='PosibleOcurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombee de posibles ocurrencia')),
                ('valor', models.IntegerField(help_text='Valor de posible ocurrencia Debe de ser entre 0 y 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del proceso')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descipcion del proceso')),
            ],
        ),
        migrations.CreateModel(
            name='RiesgoAsociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de los riesgos asociados')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del tipo de riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.CharField(db_index=True, help_text='ID de la matriz de riesgo', max_length=10, primary_key=True, serialize=False, verbose_name='Id matriz')),
                ('fecha_riesgo', models.DateField(help_text='Fecha de identificación riesgo', verbose_name='Fecha identificacion riesgo')),
                ('codigo_riesgo', models.CharField(help_text='Código del riesgo', verbose_name='Codigo del riesgo')),
                ('descripcion', models.CharField(help_text='Definición y Descripción del riesgo', max_length=255, verbose_name='Definición y Descripción del riesgo')),
                ('causas', models.TextField(help_text='Causas (un riesgo puede tener mas de una causa) Vulnerabilidad - Amenazas', verbose_name='Causas de riesgo')),
                ('efectos', models.CharField(help_text='Definición de los efectos de materialización del riesgo identificado', max_length=255, verbose_name='Definición de los efectos del riesgo')),
                ('afectacion', models.CharField(help_text='Riesgo afecta infraestructua crítica', max_length=255, verbose_name='Afecta infraestructua crítica')),
                ('riesgo_afectacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'NA')], help_text='Riesgo afecta infraestructua crítica', max_length=2, verbose_name='Riesgo afecta')),
                ('informacion_asosiada', models.CharField(help_text='Activos de Información Asociados', max_length=255, verbose_name='Activos de informacion')),
                ('tipo_activo', models.CharField(help_text='Tipo de activo vinculado', max_length=255, verbose_name='Tipo de activo')),
                ('criterio_activo', models.CharField(help_text='Criticidad del activo', max_length=255, verbose_name='Criticidad del activo')),
                ('dueño_riesgo', models.CharField(help_text='Dueño o propietario del riesgo', max_length=100, verbose_name='Dueño del riesgo')),
                ('rol_dueño_riesgo', models.CharField(help_text='Rol del dueño o propietario del riesgo', max_length=30, verbose_name='Rol dueño del riesgo')),
                ('tipo_impacto', models.CharField(choices=[('Continuidad Operativa', 'Continuidad Operativa'), ('Imagen', 'Imagen'), ('Legal', 'Legal')], help_text='Tipo de Impacto', max_length=50, verbose_name='Tipo de Impacto')),
                ('controles', models.CharField(help_text='Controles existentes', max_length=255, verbose_name='Controles existentes')),
                ('zona_riego', models.CharField(choices=[('BAJA', 'BAJA'), ('MODERADA', 'MODERADA'), ('ALTA', 'ALTA'), ('EXTREMA', 'EXTREMA')], help_text='Zona de riesgo', max_length=20, verbose_name='Zona de riesgo')),
                ('aceptado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'NA')], help_text='Se acepta o no', max_length=2, verbose_name='¿SE ACEPTA?')),
                ('tratamiento', models.CharField(help_text='Tratamiento Controles a implementar', max_length=255, verbose_name='Tratamiento Controles a implementar')),
                ('tipo_control', models.CharField(help_text='Tipo de control', max_length=50, verbose_name='Tipo de control')),
                ('impacto', models.ForeignKey(help_text='Impacto', on_delete=django.db.models.deletion.CASCADE, to='matriz.impacto', verbose_name='Impacto')),
                ('user', models.ForeignKey(help_text='Usuario que realiza la accion al crear una matriz de risgo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('opcion_tratamiento', models.ForeignKey(help_text='Nombe de opcion de tratamiento de riego', on_delete=django.db.models.deletion.CASCADE, to='matriz.opciontratamiento', verbose_name='Nombe de opcion de tratamiento de riego')),
                ('Posibilidad_ocurrencia', models.ForeignKey(help_text='Posibilidad de Ocurrencia', on_delete=django.db.models.deletion.CASCADE, to='matriz.posibleocurrencia', verbose_name='Posibilidad de Ocurrencia')),
                ('proceso', models.ForeignKey(help_text='Proceso', on_delete=django.db.models.deletion.CASCADE, to='matriz.procesos', verbose_name='Proceso')),
                ('riesgo_asociados', models.ManyToManyField(to='matriz.riesgoasociados')),
                ('riesgo', models.ForeignKey(help_text='Riesgo', on_delete=django.db.models.deletion.CASCADE, to='matriz.riesgos', verbose_name='Tipo de riesgo')),
            ],
        ),
    ]
