# Generated by Django 5.2 on 2025-05-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_alter_empresa_codigo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del software')),
                ('vesion', models.CharField(max_length=50, verbose_name='Versión de software')),
                ('objectivo_general', models.CharField(max_length=500, verbose_name='Objetivos generales del software')),
                ('objetivo_especifico', models.CharField(max_length=500, verbose_name='Objetivos especificos del software')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro del software')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualizacioon')),
                ('codigo_software', models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo del unico de software')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del software')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa_software', to='empresa.empresa', verbose_name='Emopresa del Software')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
    ]
